version: '3.8'

services:
  ui:
    build: ./ui
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app/node_modules
      - ./ui:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build: ./api
    restart: always
    ports:
      - 5050:5050
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
    depends_on:
      - mongo
