version: '3.8'

services:
  ui:
    build: ./ui
    ports:
      - 3000:3000
    volumes:
      - ./app/node_modules
      - ./ui:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build: ./api
    ports:
      - 5050:5050
